; PlatformIO Project Configuration File for the team's micromouse hardware
; MMRC26 Micromouse Maze Solver

[platformio]
default_envs = esp32_c3_supermini
src_dir = firmware/src
include_dir = firmware/include

[env:esp32_c3_supermini]
platform = espressif32 @ 6.12.0
board = esp32-c3-devkitm-1
board_build.flash_mode = dio
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -I firmware/include
    -O2
    -D ROBOT_ESP32_C3=1
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    pololu/VL53L0X @ 1.3.1

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -I firmware/include
    -O2
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

lib_deps =
    pololu/VL53L0X @ ^1.3.1

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -I firmware/include
    -O2
    -D CORE_DEBUG_LEVEL=0

lib_deps =
    pololu/VL53L0X @ ^1.3.1
